joint_names: ["arm_left_1_joint","arm_left_2_joint","arm_left_3_joint","arm_left_4_joint","arm_left_5_joint","arm_left_6_joint","arm_left_7_joint"]
action_name: /arm_left/joint_trajectory_controller/follow_joint_trajectory
service_ns: /arm_left/driver

# single positions
home: [[0,0,0,0,0,0,0]]
folded: [[0.9599, 1.5708, 0, 1.100, 1.4400, 0.6981, 0]]
side: [[-0.9599, -1.6581, 1.0472, 1.6581, 1.0472, 0.6981, 0]]
