joint_names: ["arm_left_1_joint","arm_left_2_joint","arm_left_3_joint","arm_left_4_joint","arm_left_5_joint","arm_left_6_joint","arm_left_7_joint"]
action_name: /arm_left/joint_trajectory_controller/follow_joint_trajectory
service_ns: /arm_left/driver

# single positions
home: [[0,0,0,0,0,0,0]]
folded: [[-0.87, 1.57, 0, 1.57, 0, 0, 0]]
