joint_names: ["arm_right_1_joint","arm_right_2_joint","arm_right_3_joint","arm_right_4_joint","arm_right_5_joint","arm_right_6_joint","arm_right_7_joint"]
action_name: /arm_right/joint_trajectory_controller/follow_joint_trajectory
service_ns: /arm_right/driver

# single positions
home: [[0,0,0,0,0,0,0]]
folded: [[-0.87, 1.57, 0, 1.57, 0, 0, 0]]
