name: base_controller

defaults:
  eds_pkg: cob_hardware_config
  eds_file: "cob4-6/config/Elmo.dcf"

modules:
  - name: fl_caster_rotation_joint
    id: 1
    dcf_overlay: # "ObjectID" : "ParameterValue" (both as strings)
      "6098": "19" # homing method
  - name: fl_caster_r_wheel_joint
    id: 2
    dcf_overlay: # "ObjectID" : "ParameterValue" (both as strings)
      "6098": "35" # homing method
  - name: fr_caster_rotation_joint
    id: 3
    dcf_overlay: # "ObjectID" : "ParameterValue" (both as strings)
      "6098": "19" # homing method
  - name: fr_caster_r_wheel_joint
    id: 4
    dcf_overlay: # "ObjectID" : "ParameterValue" (both as strings)
      "6098": "35" # homing method
  - name: b_caster_rotation_joint
    id: 5
    dcf_overlay: # "ObjectID" : "ParameterValue" (both as strings)
      "6098": "19" # homing method
  - name: b_caster_r_wheel_joint
    id: 6
    dcf_overlay: # "ObjectID" : "ParameterValue" (both as strings)
      "6098": "35" # homing method

