name: base_controller

defaults:
  eds_pkg: cob_hardware_config
  eds_file: "cob4-6/config/Elmo.dcf"

modules:
  - name: fl_caster_rotation_joint
    id: 1
  - name: fl_caster_r_wheel_joint
    id: 2
  - name: bl_caster_rotation_joint
    id: 3
  - name: bl_caster_r_wheel_joint
    id: 4
  - name: br_caster_rotation_joint
    id: 5
  - name: br_caster_r_wheel_joint
    id: 6

