# canopen parameter
can_module: PCAN
can_baudrate: 500
max_accelerations: [0.1,0.1]

# trajectory controller parameters
ptp_vel: 0.1 # rad/sec
ptp_acc: 0.1 # rad/sec^2
max_error: 0.01 # rad
frequency: 68

joint_names: [head_powerball_bottom_joint, head_powerball_side_joint]
module_ids: [7,8]
devices: ["/dev/pcan32", "/dev/pcan32"]
