joint_names: ["tray_1_joint", "tray_2_joint", "tray_3_joint"]
home: [[0.0, 0.0, 0.0]]
deliverup: [[0.0, 0.0, -1.5708]]
displayup: [[0.0, 0.0, 1.5708]]
deliverdown: [[-0.85, 0.0, -0.725]]
displaydown: [[-0.85, 0.0, 2.416]]
folded: [[-1.3, 0.0, 1.3]]
