joint_names: ["torso_pan_joint", "torso_tilt_joint"]
action_name: /torso/joint_trajectory_controller/follow_joint_trajectory
service_ns: /torso/driver

home: [[0.0,0.0]]
right: [[0.2,0.0]]
down: [[-0.48,0.0]]
exhibition: [[0.48,0.0]]
