#group:
#  group_name: <group_name>
#  component_name: <component_name>
#  buttons: [[button_name1,function_name1,parameter_name2,
#    [button_name2,function_name2,parameter_name2]]

group1:
  group_name: base
  component_name: base
  buttons: [[stop,stop,omni],
    [init,trigger,init],
    [recover,trigger,recover]]
group2:
  group_name: arm_left
  component_name: arm_left
  buttons: [[stop,stop],
    [init,init],
    [recover,recover],
    [home,move,home],
    [folded,move,folded],
    [side, move, side],
    [ship, move, ship],
    [hello_demo, move, hello_demo]]
group3:
  group_name: arm_right
  component_name: arm_right
  buttons: [[stop,stop],
    [init,init],
    [recover,recover],
    [home,move,home],
    [folded,move,folded],
    [side, move, side],
    [ship, move, ship],
    [hello_demo, move, hello_demo]]
#group4:
#  group_name: gripper_left
#  component_name: gripper_left
#  buttons: [[stop,stop],
#    [recover,recover],
#    [home,move,home],
#    [open,move,open],
#    [close, move, close],
#    [spread, move, spread],
#    [showCamera, trigger, showCamera_left]]
#group5:
#  group_name: gripper_right
#  component_name: gripper_right
#  buttons: [[stop,stop],
#    [recover,recover],
#    [home,move,home],
#    [open,move,open],
#    [close, move, close],
#    [spread, move, spread],
#    [showCamera, trigger, showCamera_right]]
group6:
  group_name: torso
  component_name: torso
  buttons: [[stop,stop],
    [init,init],
    [recover,recover],
    [home,move,home]]

group61:
  group_name: torso
  component_name: demo
  buttons: [[bow,trigger,bow]]

#group7:
#  group_name: sensorring
#  component_name: sensorring
#  buttons: [[stop,stop],
#    [init,init],
#    [recover,recover],
#    [front,move,front],
#    [left,move,left],
#    [right,move,right]]
group8:
  group_name: mimic
  component_name: demo
  buttons: [[laughing,trigger,setMimicLaughing],
    [asking,trigger,setMimicAsking],
    [SayYes,trigger,setMimicYes],
    [blinkingRight,trigger,setMimicBlinkingRight],
    [confused,trigger,setMimicConfused],
    [angry,trigger,setMimicAngry],
    [sleep,trigger,setMimicFallingAsleep]]
group9:
  group_name: light
  component_name: demo
  buttons: [[cyanBreath,trigger,setLightCyanBreath],
    [cyan,trigger,setLightCyan],
    [red,trigger,setLightRed],
    [green,trigger,setLightGreen],
    [cyanSweep,trigger,setLightCyanSweep]]
group91:
  group_name: sound
  component_name: demo
  buttons: [[playSound,trigger,playSound],
    [noConnection,trigger,soundNoConnection],
    [negative,trigger,soundNegative],
    [starting,trigger,soundStarting],
    [hello,trigger,soundHello]]
