joint_names: [arm_left_1_joint, arm_left_2_joint, arm_left_3_joint, arm_left_4_joint, arm_left_5_joint, arm_left_6_joint, arm_left_7_joint]

device: /dev/pcan3
baudrate: 500K
sync_interval: 10
chains: ["arm_left_controller"]
