host: 10.4.1.99
port: "9100" # alternative syntax: !!str 9100
threshold_linear_slow: 0.05
threshold_linear_fast: 0.3
threshold_angular_fast: 2.5
marker_type: 8 # http://www.ros.org/wiki/rviz/DisplayTypes/Marker, not all are supported
scale_x: 0.01
scale_y: 0.01
scale_z: 0.01
 