#all
joint_names: [sensorring_joint]

# trajectory controller parameters
ptp_vel: 1.0 # rad/sec
ptp_acc: 0.2 # rad/sec^2
max_error: 0.25 # rad
overlap_time: 0.4
frequency: 68
operation_mode: velocity

# controller_adapter_gazebo
update_rate: 33.0
max_vel_command_silence: 0.5
