joint_names: ["tray_1_joint", "tray_2_joint", "tray_3_joint"]
home: [[0.0, 0.0, 0.0]]
deliverup: [[0.0, 0.0, 0.0]]
deliverdown: [[-0.9, 0.0, 0.9]]
displayup: [[0.0, 0.0, -3.14]]
displaydown: [[-0.9, 0.0, -2.24]]
storetray: [[-1.35, 0.0, 2.96]]
