joint_names: ["tray_1_joint", "tray_2_joint", "tray_3_joint"]

devices:
  - name: /dev/pcan32
    baudrate: 500K
    sync_interval: 10
# - name: /dev/pcan32
#   baudrate: 1M
#   sync_interval: 5
chains: ["tray_controller"]
