threshold_warning: 20 # % of battery level
zhreshold_error: 10 # % of battery level
threshold_critical: 5 # % of battery level

enable_light: false
num_leds: 1
light_components: ['light']

enable_sound: false
sound_components: ['sound']
