joint_names: [arm_right_1_joint, arm_right_2_joint, arm_right_3_joint, arm_right_4_joint, arm_right_5_joint, arm_right_6_joint, arm_right_7_joint]

device: /dev/pcan2
baudrate: 500K
sync_interval: 10
chains: ["arm_right_controller"]
