## Cartesian controller
cartesian_controller:
  update_rate: 50.0

  # twist controller parameters
  chain_base_link: arm_right_base_link
  chain_tip_link: arm_right_7_link
  base_compensation: false
  base_active: false
  base_ratio: 0.0
  max_vel_lin: 0.5
  max_vel_rot: 0.5

  # damping parameters
  damping_method: 0
  eps: 0.005
  lambda0: 0.1

  # frame_tracker + interactive_marker
  tracking_frame: arm_right_7_target
  root_frame: odom_combined
  movable_trans: true
  movable_rot: true
  pid_trans: {p: 4.0, i: 0.0, d: 0.0, i_clamp: 0.0}
  pid_rot: {p: 4.0, i: 0.0, d: 0.0, i_clamp: 0.0}
