# NOT USED YET IN BATTERY MONITOR --> NEEDS TO BE IMPLEMENTED FIRST
threshold_warning: 30 # % of battery level
threshold_warning: 10 # % of battery level

enable_light: true
num_leds: 58
led_components: [light_torso]

enable_sound: true
sound_components: [sound]
