<<<<<<< HEAD
=======
# rotation mode (0=fixed angle as defined  by rotation_angle, 1=automatic upright rotation against gravity using reference coordinate frame with upwards directed z-axis, 2=as 1 but image rotation only in 90deg steps -> faster)
# int
rotation_mode: 1

# image rotation [in deg] (especially efficient with 0, 90, 180, 270 deg)
# double
rotation_angle: 0

# reference world coordinate frame with z-axis pointing upwards (= against gravity direction)
# string
reference_frame: base_link

>>>>>>> e9eedebc3e2ebf534e7ffb4ee4d96873e6c9ee96
# flip color image
# bool
flip_color_image: true

<<<<<<< HEAD
# rotation [in deg] (90, 180, 270 deg), 0=automatic mode, works only with cob3 head axis at the moment
# int
rotation: 90

# flip point cloud
# bool
flip_pointcloud: false

# point cloud data format
# string (xyz or xyzrgb)
pointcloud_data_format: xyzrgb
=======
# flip point cloud (usually unnecessary because tf takes care of this with original point cloud)
# bool
flip_pointcloud: true
>>>>>>> e9eedebc3e2ebf534e7ffb4ee4d96873e6c9ee96

# display warning if transformation not available
# bool
display_warnings: false
<<<<<<< HEAD

# display timing information
# bool
display_timing: false
=======
>>>>>>> e9eedebc3e2ebf534e7ffb4ee4d96873e6c9ee96
