name: sensorring_controller

defaults:
  eds_pkg: cob_hardware_config
  eds_file: "cob4-2/config/Elmo.dcf"

modules:
  - name: sensorring_joint
    id: 73
    dcf_overlay: # "ObjectID": "ParameterValue" (both as strings)
      "6098": "35" #  homing method
      #"1016sub1" : "0x7F0064" # heartbeat timeout of 100 ms for master at 127
      "1017": "100" # heartbeat producer

