arm_left_uri:
  - arm_left_1_joint
  - arm_left_2_joint
  - arm_left_3_joint
  - arm_left_4_joint
  - arm_left_5_joint
  - arm_left_6_joint
  - arm_left_7_joint
arm_right_uri:
  - arm_right_1_joint
  - arm_right_2_joint
  - arm_right_3_joint
  - arm_right_4_joint
  - arm_right_5_joint
  - arm_right_6_joint
  - arm_right_7_joint
components:
 - head
 - arm_left
 - arm_right
 - torso
 - sensorring
 - gripper_left
 - gripper_right
 - base
led_mode:
  - [1,0,0,0] #mode 0 base
  - [1,1,0,0] #mode 1 arm left cartesian
  - [0,0,1,1] #mode 1 arm right cartesian
  - [0,0,1,0] #mode 1 arm left joints
  - [0,1,0,0] #mode 1 arm left joints
  - [1,1,1,1] #mode 1 autmoves
  - [1,0,0,1] #mode 1 head torso sensorring
