defaults:
  eds_pkg: cob_hardware_config
  eds_file: "cob4-2/config/Elmo.dcf"

nodes:
  - name: torso_2_joint
    id: 32
    dcf_overlay: # "ObjectID": "ParameterValue" (both as strings)
      "6083": "6000" # mgrad/sec²
      "6084": "6000"
      "60C5": "6000"
      "60C6": "6000"
  - name: torso_3_joint
    id: 33
    dcf_overlay: # "ObjectID": "ParameterValue" (both as strings)
      "6083": "80000"
      "6084": "80000"
      "60C5": "80000"
      "60C6": "80000"
