host: 141.3.80.115
angle_resolution: 0.25 #deg
scan_frequency: 25 #hz
inverted: true
frame_id: /base_laser_rear_link
scan_intervals: [[-0.785, 2.0]] #[rad] these intervals are included to the scan
#scan_intervals: [[-2.0, 0.785]] #[rad] these intervals are included to the scan
